import csv

enriched = [
  {
    "SIREN": "775676182", "SIRET siège": "77567618200105",
    "Nom": "LE SOUVENIR FRANCAIS", "Sigle": "",
    "Forme juridique": "Association déclarée (9220)",
    "Code NAF": "94.99Z", "Activité": "Autres organisations fonctionnant par adhésion volontaire",
    "Date création": "1900-01-01", "Statut": "Actif",
    "Adresse siège": "20 RUE EUGENE FLACHAT", "Code postal": "75017", "Commune": "PARIS", "Département": "75",
    "GPS": "48.887285, 2.299390", "Tranche effectif": "10-19 salariés",
    "Nb établissements": "2053", "Nb étab. ouverts": "1977", "Catégorie": "PME",
    "Est association": "Oui", "Est ESS": "Oui", "Id RNA": "W751004722",
    "Convention collective (IDCC)": "9999", "Sanctions": "Aucune", "Procédures collectives": "Aucune",
    "Labels": "",
    "Président(s)": "Frédéric Perrot / Dominique Andre / Serge Barcellini / Jean-Claude Allard / Laurent Robin / Jean-François Beolor / Stéphane Mallet / Patrice Castel / Marcel Mathieu / Corinne Richard-Mangeot / Patrick Durand / Abdelkader Noufel / Renée Bail / Georges Evariste / Jacques Malivert",
    "Délégués généraux": "Viviane Courtin / Alain Allemand (adj.) / Jean-Paul Jouval / Marc Prive / Jacqueline Daurat / Jean-Louis Beziat / Richard Neuillet / Anne-Françoise Viallon / Nicole Schira / Jean-Luc François / Guy Rochet / René Drouin / Jean-Marie Beyer / Lilianes Schlegel / Gérard Carreras / Philippe Pain / Jean-Luc Miola",
    "Trésorier(s)": "Nathalie Zorzin / Émilie Bertino / Hélène Godia / Carine Mallet / Jocelyne Bernard / Christine Thomas / Danielle Gremont / Francis Flourou / Jean-Claude Tibère-Inglesse / Daniel Leveau",
    "Secrétaire(s) général": "François Fouré / Pierre-Marie Duwez / Aurélien Michel / Christian Evesque / André Georges / Alain Buesa",
    "Autres représentants": "Henri Martin / Gilles Glin / Thierry Perrin / Yannick Ponce / Joseph Vivier / Fabiola Escaich (Coordinatrice) / Alain Maurin (Chargé mission) / Bernard Quere (RAF) / Emilie David (Resp. formations) / Yann Guiot / Maguelone Vahid",
    "CA (€)": "", "Résultat net (€)": "", "Total bilan (€)": "", "Capitaux propres (€)": "",
    "Téléphone": "Non disponible open data", "Email": "Non disponible open data", "Site web": "Non disponible open data",
  },
  {
    "SIREN": "390459246", "SIRET siège": "39045924600042",
    "Nom": "OFFICE CENTRAL COOPERATION ECOLE DU NORD (OCCE)", "Sigle": "OCCE",
    "Forme juridique": "Association déclarée (9220)",
    "Code NAF": "94.99Z", "Activité": "Autres organisations fonctionnant par adhésion volontaire",
    "Date création": "1989-04-12", "Statut": "Actif",
    "Adresse siège": "543 RUE D'ARRAS", "Code postal": "59500", "Commune": "DOUAI", "Département": "59",
    "GPS": "50.365289, 3.069771", "Tranche effectif": "3-5 salariés",
    "Nb établissements": "1549", "Nb étab. ouverts": "1545", "Catégorie": "PME",
    "Est association": "Oui", "Est ESS": "Oui", "Id RNA": "W593001249",
    "Convention collective (IDCC)": "1518", "Sanctions": "Aucune", "Procédures collectives": "Aucune",
    "Labels": "",
    "Président(s)": "", "Délégués généraux": "",
    "Trésorier(s)": "", "Secrétaire(s) général": "",
    "Autres représentants": "Vincent Lecerf / Chloe Thebert / Dominique Thorez",
    "Directeur": "Hélène Menard Cyhanyk",
    "CA (€)": "", "Résultat net (€)": "", "Total bilan (€)": "", "Capitaux propres (€)": "",
    "Téléphone": "Non disponible open data", "Email": "Non disponible open data", "Site web": "Non disponible open data",
  },
  {
    "SIREN": "828160069", "SIRET siège": "82816006900039",
    "Nom": "OGF SERVICES FUNERAIRES", "Sigle": "",
    "Forme juridique": "SAS (5710)",
    "Code NAF": "96.03Z", "Activité": "Services funéraires",
    "Date création": "2017-02-28", "Statut": "Actif",
    "Adresse siège": "6 RUE DU GENERAL AUDRAN (Immeuble Canopy)", "Code postal": "92400", "Commune": "COURBEVOIE", "Département": "92",
    "GPS": "48.889946, 2.254961", "Tranche effectif": "3-5 salariés (siège)",
    "Nb établissements": "1551", "Nb étab. ouverts": "1544", "Catégorie": "GE",
    "Est association": "Non", "Est ESS": "Non", "Id RNA": "",
    "Convention collective (IDCC)": "0759, 9999", "Sanctions": "Aucune", "Procédures collectives": "Aucune",
    "Labels": "ORIAS - Mandataire d'Assurance n°25004824 (inscrit 2025-06-06)",
    "Président(s)": "Alain COTTET (né 1968, en poste depuis 2020-11-17)",
    "Délégués généraux": "", "Trésorier(s)": "", "Secrétaire(s) général": "",
    "Autres représentants": "DELOITTE & ASSOCIES (Commissaire aux comptes titulaire, depuis 2017-03-06)",
    "CA (€)": "2 192 551 (exercice 2024)", "Résultat net (€)": "-60 689 490 (exercice 2025)", "Total bilan (€)": "1 475 530 128 (2025)", "Capitaux propres (€)": "713 495 040 (2025)",
    "Téléphone": "Non disponible open data", "Email": "Non disponible open data", "Site web": "Non disponible open data",
  },
  {
    "SIREN": "329425268", "SIRET siège": "32942526800029",
    "Nom": "OCCE 67 COOPERATIVES SCOLAIRES DU BAS-RHIN", "Sigle": "",
    "Forme juridique": "Union d'associations (9260)",
    "Code NAF": "94.99Z", "Activité": "Autres organisations fonctionnant par adhésion volontaire",
    "Date création": "1984-01-01", "Statut": "Actif",
    "Adresse siège": "25 RUE GIOBERTI", "Code postal": "67200", "Commune": "STRASBOURG", "Département": "67",
    "GPS": "48.591902, 7.699047", "Tranche effectif": "1-2 salariés",
    "Nb établissements": "806", "Nb étab. ouverts": "787", "Catégorie": "PME",
    "Est association": "Oui", "Est ESS": "Oui", "Id RNA": "",
    "Convention collective (IDCC)": "1518", "Sanctions": "Aucune", "Procédures collectives": "Aucune",
    "Labels": "", "Président(s)": "", "Délégués généraux": "", "Trésorier(s)": "", "Secrétaire(s) général": "", "Autres représentants": "",
    "CA (€)": "", "Résultat net (€)": "", "Total bilan (€)": "", "Capitaux propres (€)": "",
    "Téléphone": "Non disponible open data", "Email": "Non disponible open data", "Site web": "Non disponible open data",
  },
  {
    "SIREN": "342006491", "SIRET siège": "34200649100019",
    "Nom": "SOCIETE NATIONALE D'ENTRAIDE DE LA MEDAILLE MILITAIRE (SNEMM)", "Sigle": "SNEMM",
    "Forme juridique": "Association déclarée (9220)",
    "Code NAF": "94.99Z", "Activité": "Autres organisations fonctionnant par adhésion volontaire",
    "Date création": "1987-01-01", "Statut": "Actif",
    "Adresse siège": "36 RUE DE LA BIENFAISANCE", "Code postal": "75008", "Commune": "PARIS", "Département": "75",
    "GPS": "48.876632, 2.316058", "Tranche effectif": "6-9 salariés",
    "Nb établissements": "666", "Nb étab. ouverts": "630", "Catégorie": "PME",
    "Est association": "Oui", "Est ESS": "Oui", "Id RNA": "W751010031",
    "Convention collective (IDCC)": "0029, 2128", "Sanctions": "Aucune", "Procédures collectives": "Aucune",
    "Labels": "",
    "Président(s)": "José Miguel Real / Lucien Datin / Erick Cresson / Luc Nevou / Didier Brissac / Pascal Vigne",
    "Délégués généraux": "", "Trésorier(s)": "Pascal Lenne / Jean-Noël Rouffiange / Roland Jolly / Robin Christophe",
    "Secrétaire(s) général": "Patrick Lamy",
    "Autres représentants": "Christian Duverne (Vice-Président) / Fabien Fromonot",
    "CA (€)": "", "Résultat net (€)": "", "Total bilan (€)": "", "Capitaux propres (€)": "",
    "Téléphone": "Non disponible open data", "Email": "Non disponible open data", "Site web": "Non disponible open data",
  },
  {
    "SIREN": "391694064", "SIRET siège": "39169406400034",
    "Nom": "ASS DEPART OFFICE CTRAL COOPER ECOLE 57 (OCCE)", "Sigle": "OCCE",
    "Forme juridique": "Union d'associations (9260)",
    "Code NAF": "94.99Z", "Activité": "Autres organisations fonctionnant par adhésion volontaire",
    "Date création": "1993-01-01", "Statut": "Actif",
    "Adresse siège": "1 B RUE NICOLAS JUNG", "Code postal": "57050", "Commune": "METZ", "Département": "57",
    "GPS": "49.133347, 6.154819", "Tranche effectif": "1-2 salariés",
    "Nb établissements": "591", "Nb étab. ouverts": "589", "Catégorie": "PME",
    "Est association": "Oui", "Est ESS": "Oui", "Id RNA": "",
    "Convention collective (IDCC)": "1518", "Sanctions": "Aucune", "Procédures collectives": "Aucune",
    "Labels": "", "Président(s)": "", "Délégués généraux": "", "Trésorier(s)": "", "Secrétaire(s) général": "", "Autres représentants": "",
    "CA (€)": "", "Résultat net (€)": "", "Total bilan (€)": "", "Capitaux propres (€)": "",
    "Téléphone": "Non disponible open data", "Email": "Non disponible open data", "Site web": "Non disponible open data",
  },
  {
    "SIREN": "391238904", "SIRET siège": "39123890400067",
    "Nom": "ASS OFFICE CENTRAL COOPERATION ECOLE (OCCE 54)", "Sigle": "OCCE 54",
    "Forme juridique": "Association déclarée (9220)",
    "Code NAF": "94.99Z", "Activité": "Autres organisations fonctionnant par adhésion volontaire",
    "Date création": "1989-06-22", "Statut": "Actif",
    "Adresse siège": "4 ALLEE D'ENGHIEN", "Code postal": "54600", "Commune": "VILLERS-LES-NANCY", "Département": "54",
    "GPS": "48.655072, 6.137501", "Tranche effectif": "Non employeur",
    "Nb établissements": "534", "Nb étab. ouverts": "532", "Catégorie": "PME",
    "Est association": "Oui", "Est ESS": "Oui", "Id RNA": "W543000517",
    "Convention collective (IDCC)": "1518", "Sanctions": "Aucune", "Procédures collectives": "Aucune",
    "Labels": "", "Président(s)": "", "Délégués généraux": "", "Trésorier(s)": "", "Secrétaire(s) général": "", "Autres représentants": "",
    "CA (€)": "", "Résultat net (€)": "", "Total bilan (€)": "", "Capitaux propres (€)": "",
    "Téléphone": "Non disponible open data", "Email": "Non disponible open data", "Site web": "Non disponible open data",
  },
  {
    "SIREN": "331385195", "SIRET siège": "33138519500010",
    "Nom": "OCCE SECTEUR DU DEPARTEMENT DU HAUT RHIN", "Sigle": "",
    "Forme juridique": "Union d'associations (9260)",
    "Code NAF": "94.99Z", "Activité": "Autres organisations fonctionnant par adhésion volontaire",
    "Date création": "1952-02-01", "Statut": "Actif",
    "Adresse siège": "12 RUE MESSIMY", "Code postal": "68000", "Commune": "COLMAR", "Département": "68",
    "GPS": "48.071591, 7.352802", "Tranche effectif": "1-2 salariés",
    "Nb établissements": "523", "Nb étab. ouverts": "493", "Catégorie": "PME",
    "Est association": "Oui", "Est ESS": "Oui", "Id RNA": "",
    "Convention collective (IDCC)": "1518", "Sanctions": "Aucune", "Procédures collectives": "Aucune",
    "Labels": "", "Président(s)": "", "Délégués généraux": "", "Trésorier(s)": "", "Secrétaire(s) général": "", "Autres représentants": "",
    "CA (€)": "", "Résultat net (€)": "", "Total bilan (€)": "", "Capitaux propres (€)": "",
    "Téléphone": "Non disponible open data", "Email": "Non disponible open data", "Site web": "Non disponible open data",
  },
  {
    "SIREN": "328368915", "SIRET siège": "32836891500067",
    "Nom": "OFFICE CENTRAL COOPERATION A L ECOLE (OCCE 71)", "Sigle": "OCCE 71",
    "Forme juridique": "Association déclarée (9220)",
    "Code NAF": "94.99Z", "Activité": "Autres organisations fonctionnant par adhésion volontaire",
    "Date création": "1983-11-01", "Statut": "Actif",
    "Adresse siège": "ESPACE JEAN ZAY 4 RUE JULES FERRY", "Code postal": "71100", "Commune": "CHALON-SUR-SAONE", "Département": "71",
    "GPS": "46.797978, 4.867026", "Tranche effectif": "1-2 salariés",
    "Nb établissements": "476", "Nb étab. ouverts": "473", "Catégorie": "PME",
    "Est association": "Oui", "Est ESS": "Oui", "Id RNA": "W712001941",
    "Convention collective (IDCC)": "1518", "Sanctions": "Aucune", "Procédures collectives": "Aucune",
    "Labels": "", "Président(s)": "", "Délégués généraux": "", "Trésorier(s)": "", "Secrétaire(s) général": "",
    "Autres représentants": "Christian Duparay (Coordinateur) / Michel Schaeffer / Stéphanie Futin",
    "CA (€)": "", "Résultat net (€)": "", "Total bilan (€)": "", "Capitaux propres (€)": "",
    "Téléphone": "Non disponible open data", "Email": "Non disponible open data", "Site web": "Non disponible open data",
  },
  {
    "SIREN": "390403046", "SIRET siège": "39040304600068",
    "Nom": "OFFICE CENTRAL COOPERATION A L'ECOLE (OCCE)", "Sigle": "OCCE",
    "Forme juridique": "Association déclarée (9220)",
    "Code NAF": "94.99Z", "Activité": "Autres organisations fonctionnant par adhésion volontaire",
    "Date création": "1992-12-02", "Statut": "Actif",
    "Adresse siège": "9 ROUTE DE SANDILLON", "Code postal": "45150", "Commune": "FEROLLES", "Département": "45",
    "GPS": "47.834875, 2.109733", "Tranche effectif": "1-2 salariés",
    "Nb établissements": "467", "Nb étab. ouverts": "457", "Catégorie": "PME",
    "Est association": "Oui", "Est ESS": "Oui", "Id RNA": "W452001001",
    "Convention collective (IDCC)": "1518", "Sanctions": "Aucune", "Procédures collectives": "Aucune",
    "Labels": "", "Président(s)": "", "Délégués généraux": "", "Trésorier(s)": "", "Secrétaire(s) général": "", "Autres représentants": "",
    "CA (€)": "", "Résultat net (€)": "", "Total bilan (€)": "", "Capitaux propres (€)": "",
    "Téléphone": "Non disponible open data", "Email": "Non disponible open data", "Site web": "Non disponible open data",
  },
]

all_keys = []
for row in enriched:
    for k in row:
        if k not in all_keys:
            all_keys.append(k)

output = "C:/Users/pierr/Documents/test_10_entreprises_COMPLET.csv"
with open(output, "w", newline="", encoding="utf-8-sig") as f:
    writer = csv.DictWriter(f, fieldnames=all_keys, delimiter=";", extrasaction="ignore")
    writer.writeheader()
    for row in enriched:
        full_row = {k: row.get(k, "") for k in all_keys}
        writer.writerow(full_row)

print(f"OK - {len(enriched)} lignes x {len(all_keys)} colonnes -> {output}")
